// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASM38VSA2J71_Q6Numa6j3EKCHj1UMbUc',
    appId: '1:529547011863:web:6e6cf300fd87a7c2dd7952',
    messagingSenderId: '529547011863',
    projectId: 'system-nabdalattaa',
    authDomain: 'system-nabdalattaa.firebaseapp.com',
    storageBucket: 'system-nabdalattaa.firebasestorage.app',
    measurementId: 'G-4Q99LDNWKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJS5uP4ZZqrav0HGUyjDr1b90cAXQoGWs',
    appId: '1:529547011863:android:79da1a21e4062a52dd7952',
    messagingSenderId: '529547011863',
    projectId: 'system-nabdalattaa',
    storageBucket: 'system-nabdalattaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASytLgF9vqRIVemuCDCEhL05o3LJUwUcQ',
    appId: '1:529547011863:ios:014065ced149cfe7dd7952',
    messagingSenderId: '529547011863',
    projectId: 'system-nabdalattaa',
    storageBucket: 'system-nabdalattaa.firebasestorage.app',
    iosBundleId: 'com.zerobugs.systemNabdAlattaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASytLgF9vqRIVemuCDCEhL05o3LJUwUcQ',
    appId: '1:529547011863:ios:014065ced149cfe7dd7952',
    messagingSenderId: '529547011863',
    projectId: 'system-nabdalattaa',
    storageBucket: 'system-nabdalattaa.firebasestorage.app',
    iosBundleId: 'com.zerobugs.systemNabdAlattaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASM38VSA2J71_Q6Numa6j3EKCHj1UMbUc',
    appId: '1:529547011863:web:e8bf2894562552e8dd7952',
    messagingSenderId: '529547011863',
    projectId: 'system-nabdalattaa',
    authDomain: 'system-nabdalattaa.firebaseapp.com',
    storageBucket: 'system-nabdalattaa.firebasestorage.app',
    measurementId: 'G-83YZRM0GBJ',
  );
}
